SHOW DATABASES;
USE BANK;

CREATE TABLE BRANCH(
    BRANCH_NAME VARCHAR(100) PRIMARY KEY,
    BRANCH_CITY VARCHAR(50),
    ASSETS BIGINT
);

CREATE TABLE CUSTOMER(
    CUSTOMER_NAME VARCHAR(100) PRIMARY KEY,
    CUSTOMER_STREET VARCHAR(100),
    CUSTOMER_CITY VARCHAR(100)
);

CREATE TABLE ACCOUNT(
    ACCOUNT_NUMBER VARCHAR(100) PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    BALANCE BIGINT
);

CREATE TABLE LOAN(
    LOAN_NUMBER VARCHAR(100) PRIMARY KEY,
    BRANCH_NAME VARCHAR(100) ,
    AMOUNT BIGINT
);

CREATE TABLE DEPOSITOR(
    CUSTOMER_NAME VARCHAR(100) ,
    ACCOUNT_NUMBER VARCHAR(100) ,
    CONSTRAINT CNFK FOREIGN KEY(CUSTOMER_NAME) REFERENCES CUSTOMER(CUSTOMER_NAME),
    CONSTRAINT ANFK FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);

CREATE TABLE BORROWER(
    CUSTOMER_NAME VARCHAR(100) ,
    LOAN_NUMBER VARCHAR (100),
    CONSTRAINT CN_FK FOREIGN KEY(CUSTOMER_NAME) REFERENCES CUSTOMER(CUSTOMER_NAME),
CONSTRAINT LNFK FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER)
);

-- ALTER TABLE DEPOSITOR ADD CONSTRAINT PRIMARY KEY(CUSTOMER_NAME,ACCOUNT_NUMBER);
-- ALTER TABLE BORROWER ADD CONSTRAINT PRIMARY KEY(CUSTOMER_NAME,LOAN_NUMBER);

