--Q1
SELECT `BORROWER`.`CUSTOMER_NAME`,LOAN.`LOAN_NUMBER`,LOAN.`AMOUNT` FROM `BORROWER` JOIN `LOAN` ON `BORROWER`.`LOAN_NUMBER`=LOAN.`LOAN_NUMBER` WHERE LOAN.`BRANCH_NAME`='REC';

--Q2

SELECT `BORROWER`.`CUSTOMER_NAME`,LOAN.`LOAN_NUMBER` AS LOAN_ID,LOAN.`AMOUNT` FROM `BORROWER` JOIN `LOAN` ON `BORROWER`.`LOAN_NUMBER`=LOAN.`LOAN_NUMBER` ;

--Q3

SELECT B.CUSTOMER_NAME,
       L.LOAN_NUMBER,
       L.AMOUNT
FROM BORROWER B
JOIN LOAN L
ON B.LOAN_NUMBER = L.LOAN_NUMBER;

--Q4

SELECT `BRANCH_NAME` FROM BRANCH WHERE `ASSETS`>SOME (SELECT `ASSETS` FROM BRANCH WHERE `BRANCH_CITY`='DURGAPUR');

--Q5

SELECT `CUSTOMER_NAME` FROM `CUSTOMER` WHERE LOWER(`CUSTOMER_NAME`) LIKE '%kumar%';

--Q6

SELECT CUSTOMER_NAME FROM `BORROWER` JOIN LOAN ON `BORROWER`.`LOAN_NUMBER`=LOAN.`LOAN_NUMBER` WHERE LOAN.`BRANCH_NAME`='REC';


--Q7

SELECT * FROM `ACCOUNT` ORDER BY `BALANCE` DESC ,`ACCOUNT_NUMBER` ASC;

--Q8 
SELECT CUSTOMER_NAME FROM `DEPOSITOR` UNION SELECT `CUSTOMER_NAME` FROM BORROWER;


--Q9

SELECT DISTINCT `DEPOSITOR`.`CUSTOMER_NAME` FROM `DEPOSITOR` JOIN `BORROWER` ON `DEPOSITOR`.`CUSTOMER_NAME`=`BORROWER`.`CUSTOMER_NAME`;

--Q10
SELECT DISTINCT CUSTOMER_NAME FROM `DEPOSITOR` WHERE `CUSTOMER_NAME` NOT IN(
    SELECT `CUSTOMER_NAME` FROM `BORROWER`
)

--Q11
SELECT AVG(BALANCE) FROM `ACCOUNT` WHERE `BRANCH_NAME` = 'REC';

--Q12
SELECT COUNT(*) AS DEPOSITOR_NO FROM `DEPOSITOR`;

--q13
SELECT `BRANCH_NAME`, COUNT(`ACCOUNT_NUMBER`) AS NO_OF_ACC FROM ACCOUNT GROUP BY `BRANCH_NAME`;

--Q14
SELECT `BRANCH_NAME` FROM `ACCOUNT` GROUP BY `BRANCH_NAME` HAVING AVG(`BALANCE`)>12000;

--Q15

SELECT `BORROWER`.`CUSTOMER_NAME`,`BORROWER`.`LOAN_NUMBER` FROM `BORROWER` JOIN `LOAN` ON `BORROWER`.`LOAN_NUMBER`=LOAN.`LOAN_NUMBER`;

--Q16

SELECT `BORROWER`.`CUSTOMER_NAME`,`BORROWER`.`LOAN_NUMBER`,LOAN.`AMOUNT` FROM `BORROWER` JOIN `LOAN` ON `BORROWER`.`LOAN_NUMBER`=LOAN.`LOAN_NUMBER` WHERE `BRANCH_NAME`='REC';

--Q17
SELECT `CUSTOMER_NAME` FROM `DEPOSITOR`
UNION
SELECT `CUSTOMER_NAME` FROM `BORROWER`;

--Q18
SELECT `CUSTOMER_NAME` FROM `BORROWER` WHERE `CUSTOMER_NAME` NOT IN (
    SELECT `CUSTOMER_NAME` FROM `DEPOSITOR`
);


--Q19
SELECT DISTINCT `CUSTOMER_NAME` FROM `BORROWER` NATURAL JOIN `DEPOSITOR`;


--Q20

SELECT BRANCH_NAME FROM `BRANCH` WHERE `ASSETS`>SOME(SELECT `ASSETS` FROM `BRANCH` WHERE `BRANCH_CITY`='KOLKATA');

--Q21

SELECT BRANCH_NAME FROM `BRANCH` WHERE `ASSETS`>ALL(SELECT `ASSETS` FROM `BRANCH` WHERE `BRANCH_CITY`='KOLKATA');

--Q22
SELECT CUSTOMER_NAME FROM `DEPOSITOR` WHERE `ACCOUNT_NUMBER` IN(
SELECT ACCOUNT_NUMBER FROM ACCOUNT WHERE `BRANCH_NAME` IN(
SELECT `BRANCH_NAME` FROM `BRANCH` WHERE `BRANCH_CITY`='KOLKATA')
);

--Q23

SELECT `CUSTOMER_NAME` FROM `DEPOSITOR` NATURAL JOIN `ACCOUNT` WHERE `BRANCH_NAME`='REC' GROUP BY `CUSTOMER_NAME` HAVING COUNT(`ACCOUNT_NUMBER`)<=1;


--Q24

SELECT COUNT(`ACCOUNT_NUMBER`),`CUSTOMER_NAME` FROM `DEPOSITOR` NATURAL JOIN `ACCOUNT` WHERE `BRANCH_NAME`='REC' GROUP BY `CUSTOMER_NAME` HAVING COUNT(`ACCOUNT_NUMBER`)>=2;


--Q25
WITH BRANCH_TOTAL AS(SELECT `BRANCH_NAME`,SUM(BALANCE) AS TOTAL FROM ACCOUNT GROUP BY `BRANCH_NAME`)
SELECT `BRANCH_NAME`,TOTAL FROM `BRANCH_TOTAL` WHERE TOTAL>(SELECT AVG(TOTAL) FROM `BRANCH_TOTAL`);

--Q26

UPDATE `ACCOUNT` SET `BALANCE` = 
    CASE 
        WHEN BALANCE>100000 THEN  BALANCE*1.06
        ELSE   BALANCE * 1.05
END;

SELECT * FROM `ACCOUNT`;